### ISSUE TITLE
pseudocode review

### ISSUE THREAD

**Issue by demiglidden** [2020-bgmp/demultiplexing-bwinnacott#1]
Hi Brendan,

Overall, I think your script touches on the goals of the assignment. All the functions
look great. This is a really solid back bone for you to start coding off of.
Generally, the logic makes sense, although I do have a concern with the way you assess the sequence
and quality score lines separate. So, for the first part, starting at line 75, you 
check to see if the indices match or not, then append them to appropriate lists.
Then, you have an elif which follows on line 83 where you compare the quality scores, but
have already designated a "fate" for the record above. Will you be able to move it? I'm not 
sure if I am imagining this issue because I don't understand your pseudecode, or if
it is actually a logical problem. I think it is worth taking a look at.

Below are some specific comments I have, prefaced by the line number the correspond with:
L04 When do you use numpy? And you'll want gzip as well.
L37 Great idea to write a function for opening all those output files.
L51 Don't you need to return something at the end of a function?
L71 You will need two for each file, so 8, right?
L76 Is this where you get rid of barcodes containing N? Because they don't exist in your dictionary?
L77 How/where is the 'unknown' counter initiated?

**Comment by demiglidden** [comment]
Slack me if you have any questions!

**Comment by bwinnacott** [comment]
Hey Demi! Great catch on some of these, will definitely take into account when translating. Super helpful! I tried to not store the information for the index records to reduce memory overall, but not sure if it will work yet...I'll let ya know how it goes!
