### ISSUE TITLE
Peer Reviewing thing

### ISSUE THREAD

**Issue by srhintonPL** [2020-bgmp/demultiplexing-bwinnacott#3]
Whats going on Brendan!!!!

So your pseudo code looks pretty darn good to me my dude. 

I have a few thoughts that came into my head while reading it.

- when generating the reverse complement sequence for the barcodes what kind of statement are you going to use? I am thinking I will use a "else : if" statement to do this, but am interested as to how you're planning on doing it because I am not confident I have found the best way. 

- also I a helpful reminder I got was to include some true false statements for my qscore cut off function to verify that it will allow a score below the cut off to be passed on.

Everything else is looking 100%!

**Comment by bwinnacott** [comment]
Sup Sam! Thanks for taking the time to read over the pseudocode. For the rev comp sequence I was thinking about using some python standard library string commands (str.translate for ex), but we'll see when I get to it. Thanks for the confidence in my structure! Let's see if it works!
